#!/usr/bin/env python3
"""Renders PixlAudio's launcher icon (logo concept C, "Glyph") for the phone and Wear OS apps.

The logo's geometry and colours live in the iOS repo's ci/make-icon.py, the single source of the logo. This script
imports it and writes Android's adaptive icon and the in-app glyph:
  <res>/mipmap-{mdpi..xxxhdpi}/ic_launcher_background.webp  the gradient tile, 108 dp (108..432 px)
  <res>/mipmap-{mdpi..xxxhdpi}/ic_launcher_foreground.webp  the white glyph with its shadows on transparent, 108 dp
  <res>/mipmap-{mdpi..xxxhdpi}/ic_launcher(_round).webp     legacy 48 dp icons (unused at minSdk 30; kept in step)
  <res>/drawable/new_monochrome.xml                         themed-icon layer: the glyph as a vector, placed like
                                                            the foreground (mipmap-anydpi-v26/ic_launcher*.xml)
for app/src/main/res and wear/src/main/res, plus, for the phone app only:
  app/src/main/res/drawable/pixelplay_base_monochrome.xml   the in-app logo glyph (About, the announcement dialog,
                                                            the full-player placeholder); same box margins as before
  app/src/main/res/drawable/monochrome_player.xml           the notification small icon (status bar, media and
                                                            lyric-sync notifications): 24 dp, glyph 22 dp tall
  assets/icon.png                                           README icon (512 px tile with transparent corners)
The icon's 1024 grid maps onto the central 72 dp of the 108 dp layers (what launcher masks show), so the Android icon
matches the iOS one. The glyph's farthest point is about 28 dp from the centre, inside the 33 dp safe-zone radius.
WebP files are lossless, as before. Needs Pillow with WebP (PIL.features.check("webp")).

Usage: python tools/make-launcher-icon.py --generator PATH/TO/pixlaudio-ios/ci/make-icon.py [--preview OUT.png]
  --notification-only  write only monochrome_player.xml (leaves the WebP layers untouched)
  --preview OUT.png  composites read back from the written files: circle and squircle masks at 48 dp (xxxhdpi and
                     mdpi), the themed monochrome icon, and the 108 dp layer with the 72 dp mask and 66 dp safe zone.
"""
import argparse
import importlib.util
import math
import os
import re

from PIL import Image, ImageChops, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES_DIRS = {"app": "app/src/main/res", "wear": "wear/src/main/res"}
DENSITIES = {"mdpi": 1, "hdpi": 1.5, "xhdpi": 2, "xxhdpi": 3, "xxxhdpi": 4}
LAYER_DP, VISIBLE_DP, SAFE_DP, LEGACY_DP = 108, 72, 66, 48
# Notification small icon: a 24 dp canvas (Android scales it into the status bar), the glyph's longer side 22 dp
# (1 dp margin; the old silhouette filled about 23 dp of its height).
NOTIFICATION_DP, NOTIFICATION_GLYPH_DP = 24, 22
HEADER = "<!-- Generated by tools/make-launcher-icon.py from the PixlAudio logo (iOS repo ci/make-icon.py). Don't edit. -->"


def load_generator(path):
    spec = importlib.util.spec_from_file_location("make_icon", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def layers(mi):
    """(background, foreground) as RGBA images covering the whole 108 dp layer at the grid's resolution."""
    extent = round(mi.N * LAYER_DP / VISIBLE_DP)  # 1536 grid px = 108 dp
    fg = mi.transparent(extent)
    fg.alpha_composite(mi.foreground(), ((extent - mi.N) // 2, (extent - mi.N) // 2))
    return mi.background(extent), fg


def save_webp(img, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path, "WEBP", lossless=True, quality=100, method=6)
    print(f"wrote {os.path.relpath(path, ROOT)} ({img.width}x{img.height} {img.mode})")


def legacy(icon, px, round_shape):
    """48 dp legacy icon: the 72 dp view (= the 1024 icon), 2 dp margin, circle or rounded square."""
    big = px * 4
    m = Image.new("L", (big, big), 0)
    inset = big * 2 / LEGACY_DP
    box = (inset, inset, big - inset, big - inset)
    if round_shape:
        ImageDraw.Draw(m).ellipse(box, fill=255)
    else:
        ImageDraw.Draw(m).rounded_rectangle(box, radius=(big - 2 * inset) * 0.18, fill=255)
    tile = icon.convert("RGBA").resize((big, big), Image.LANCZOS)
    tile.putalpha(m)
    return tile.resize((px, px), Image.LANCZOS)


def vector(path_data, comment):
    return (f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n<!-- {comment} -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp"\n    android:height="108dp"\n'
            '    android:viewportWidth="108"\n    android:viewportHeight="108">\n'
            f'    <path\n        android:fillColor="#FF000000"\n        android:pathData="{path_data}" />\n'
            '</vector>\n')


def notification_vector(mi):
    """The status-bar icon: the glyph centred on a 24 dp canvas, its longer side NOTIFICATION_GLYPH_DP."""
    x0, y0, x1, y1 = mi.glyph_bounds()
    s = NOTIFICATION_GLYPH_DP / max(x1 - x0, y1 - y0)
    dx = NOTIFICATION_DP / 2 - (x0 + x1) / 2 * s
    dy = NOTIFICATION_DP / 2 - (y0 + y1) / 2 * s
    return (f'<?xml version="1.0" encoding="utf-8"?>\n{HEADER}\n'
            '<!-- Notification small icon (status bar, media and lyric-sync notifications): the logo glyph, '
            f'{NOTIFICATION_GLYPH_DP} dp tall on {NOTIFICATION_DP} dp. Android uses only its alpha. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{NOTIFICATION_DP}dp"\n    android:height="{NOTIFICATION_DP}dp"\n'
            f'    android:viewportWidth="{NOTIFICATION_DP}"\n    android:viewportHeight="{NOTIFICATION_DP}">\n'
            f'    <path\n        android:fillColor="#FFFFFFFF"\n        android:pathData="{mi.glyph_path(s, dx, dy, 3)}" />\n'
            '</vector>\n')


def write_notification_icon(mi):
    write_text(notification_vector(mi), os.path.join(ROOT, RES_DIRS["app"], "drawable", "monochrome_player.xml"))


def write_text(text, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(path, ROOT)}")


def write_all(mi):
    bg, fg = layers(mi)
    icon = mi.render("C")  # = the composite's central 72 dp
    k = VISIBLE_DP / mi.N  # grid px -> dp
    monochrome = vector(mi.glyph_path(k, LAYER_DP / 2 - mi.N / 2 * k, LAYER_DP / 2 - mi.N / 2 * k, 2),
                        "Themed-icon layer: the logo glyph, placed exactly like ic_launcher_foreground.")
    for module, res in RES_DIRS.items():
        for density, scale in DENSITIES.items():
            d = os.path.join(ROOT, res, f"mipmap-{density}")
            layer_px, legacy_px = round(LAYER_DP * scale), round(LEGACY_DP * scale)
            save_webp(bg.resize((layer_px, layer_px), Image.LANCZOS).convert("RGB"), os.path.join(d, "ic_launcher_background.webp"))
            save_webp(fg.resize((layer_px, layer_px), Image.LANCZOS), os.path.join(d, "ic_launcher_foreground.webp"))
            save_webp(legacy(icon, legacy_px, False), os.path.join(d, "ic_launcher.webp"))
            save_webp(legacy(icon, legacy_px, True), os.path.join(d, "ic_launcher_round.webp"))
        write_text(monochrome, os.path.join(ROOT, res, "drawable", "new_monochrome.xml"))
    bx, by, side = mi.glyph_box()
    s = LAYER_DP / side
    write_text(vector(mi.glyph_path(s, -bx * s, -by * s, 2),
                      "In-app logo glyph: fills 77 % x 88.5 % of its box, like the drawable it replaced (tint it)."),
               os.path.join(ROOT, RES_DIRS["app"], "drawable", "pixelplay_base_monochrome.xml"))
    write_notification_icon(mi)
    tile = mi.masked(icon, 512)
    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    tile.save(os.path.join(ROOT, "assets", "icon.png"), "PNG", optimize=True)
    print(f"wrote assets/icon.png ({tile.width}x{tile.height})")


# ---------- preview: everything is read back from the written files ----------
def parse_vector(path, size):
    """Rasterizes the M/L/Z path of a written vector drawable (viewport 108) at size x size, independently."""
    data = re.search(r'android:pathData="([^"]+)"', open(path, encoding="utf-8").read()).group(1)
    m = Image.new("L", (size * 4, size * 4), 0)
    loops = []
    for sub in re.findall(r"M([^Z]*)Z", data):
        nums = [float(v) for v in re.findall(r"-?[\d.]+", sub)]
        loops.append([(x * size * 4 / 108, y * size * 4 / 108) for x, y in zip(nums[::2], nums[1::2])])

    def area(lp):
        return sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(lp, lp[1:] + lp[:1]))
    for lp in sorted(loops, key=lambda lp: -abs(area(lp))):
        ImageDraw.Draw(m).polygon(lp, fill=255 if area(lp) > 0 else 0)
    return m.reduce(4)


def mask_shape(px, kind):
    big = px * 4
    m = Image.new("L", (big, big), 0)
    if kind == "circle":
        ImageDraw.Draw(m).ellipse((0, 0, big - 1, big - 1), fill=255)
        return m.reduce(4)
    n, pts = 4.0, []  # squircle (superellipse n = 4, as Samsung / some Pixel shapes)
    for i in range(720):
        a = 2 * math.pi * i / 720
        c, s = math.cos(a), math.sin(a)
        pts.append((big / 2 * (1 + math.copysign(abs(c) ** (2 / n), c)), big / 2 * (1 + math.copysign(abs(s) ** (2 / n), s))))
    ImageDraw.Draw(m).polygon(pts, fill=255)
    return m.reduce(4)


def launcher_icon(res, density, dp, kind):
    """What a launcher draws: background + foreground, the central 72 dp, masked, at dp size for that density."""
    d = os.path.join(ROOT, res, f"mipmap-{density}")
    bg = Image.open(os.path.join(d, "ic_launcher_background.webp")).convert("RGBA")
    fg = Image.open(os.path.join(d, "ic_launcher_foreground.webp")).convert("RGBA")
    comp = Image.alpha_composite(bg, fg)
    cut = (comp.width - comp.width * VISIBLE_DP // LAYER_DP) // 2
    view = comp.crop((cut, cut, comp.width - cut, comp.height - cut))
    px = round(dp * DENSITIES[density])
    view = view.resize((px, px), Image.LANCZOS)
    view.putalpha(ImageChops.multiply(view.getchannel("A"), mask_shape(px, kind)))
    return view


def themed_icon(res, px, kind, bg_hex="#E5DEFF", fg_hex="#473F77"):
    """Android 13+ themed icon: the monochrome layer's alpha in the palette colour on a pastel tile."""
    layer = round(px * LAYER_DP / VISIBLE_DP)
    alpha = parse_vector(os.path.join(ROOT, res, "drawable", "new_monochrome.xml"), layer)
    cut = (layer - px) // 2
    alpha = alpha.crop((cut, cut, cut + px, cut + px))
    img = Image.new("RGBA", (px, px), bg_hex)
    img = Image.composite(Image.new("RGBA", (px, px), fg_hex), img, alpha)
    img.putalpha(mask_shape(px, kind))
    return img


def layer_view(res, px=432):
    """The 108 dp layer on a checkerboard: 72 dp mask circle (blue) and 66 dp safe zone (red)."""
    d = os.path.join(ROOT, res, "mipmap-xxxhdpi")
    fg = Image.open(os.path.join(d, "ic_launcher_foreground.webp")).convert("RGBA").resize((px, px), Image.LANCZOS)
    img = Image.new("RGBA", (px, px), (200, 200, 206, 255))
    dd = ImageDraw.Draw(img)
    for y in range(0, px, 16):
        for x in range(0, px, 16):
            if (x // 16 + y // 16) % 2:
                dd.rectangle((x, y, x + 15, y + 15), fill=(232, 232, 236, 255))
    img.alpha_composite(fg)
    dd = ImageDraw.Draw(img)
    for dp, col in ((VISIBLE_DP, (40, 90, 255, 255)), (SAFE_DP, (230, 30, 60, 255))):
        r = px * dp / LAYER_DP / 2
        dd.ellipse((px / 2 - r, px / 2 - r, px / 2 + r, px / 2 + r), outline=col, width=2)
    return img


def safe_zone_report(res):
    """Farthest opaque glyph pixel (alpha > 128, shadows excluded by threshold) from the centre, in dp."""
    d = os.path.join(ROOT, res, "mipmap-xxxhdpi")
    a = Image.open(os.path.join(d, "ic_launcher_foreground.webp")).getchannel("A")
    px, w = a.load(), a.width
    far, far_any = 0.0, 0.0
    for y in range(w):
        for x in range(w):
            r = math.hypot(x + 0.5 - w / 2, y + 0.5 - w / 2) * LAYER_DP / w
            if px[x, y] > 128:
                far = max(far, r)
            if px[x, y] > 8:
                far_any = max(far_any, r)
    return far, far_any


def font(size, bold=False):
    path = f"/usr/share/fonts/truetype/dejavu/DejaVuSans{'-Bold' if bold else ''}.ttf"
    return ImageFont.truetype(path, size) if os.path.exists(path) else ImageFont.load_default(size)


def write_preview(path):
    width, row_h = 1500, 650
    sheet = Image.new("RGBA", (width, 90 + row_h * len(RES_DIRS)), (242, 242, 246, 255))
    d = ImageDraw.Draw(sheet)
    ink, small = (60, 60, 70), font(14)
    d.text((30, 24), "PixlAudio adaptive icon (concept C), read back from the written files",
           font=font(28, True), fill=(22, 22, 29))
    for row, (module, res) in enumerate(RES_DIRS.items()):
        y0 = 90 + row * row_h
        far, far_any = safe_zone_report(res)
        d.text((30, y0), f"{module}: {res}   glyph reaches {far:.1f} dp from centre (shadow {far_any:.1f} dp); "
               f"safe zone {SAFE_DP / 2:.0f} dp, mask {VISIBLE_DP / 2:.0f} dp", font=font(17), fill=ink)
        sheet.alpha_composite(layer_view(res), (30, y0 + 40))
        d.text((246, y0 + 490), "108 dp layer: 72 dp mask (blue), 66 dp safe zone (red)", font=small, fill=ink,
               anchor="mm")
        x = 490
        for kind in ("circle", "squircle"):
            for wall in ((250, 246, 255, 255), (24, 22, 32, 255)):
                panel = Image.new("RGBA", (230, 290), wall)
                panel.alpha_composite(launcher_icon(res, "xxxhdpi", 48, kind), (19, 14))
                panel.alpha_composite(launcher_icon(res, "mdpi", 48, kind), (19, 226))
                panel.alpha_composite(themed_icon(res, 48, kind), (91, 226))
                panel.alpha_composite(themed_icon(res, 48, kind, "#2B2640", "#CFC5FF"), (163, 226))
                sheet.alpha_composite(panel, (x, y0 + 40))
                x += 245
        d.text((490 + 485, y0 + 345), "circle | squircle masks: 48 dp at xxxhdpi (192 px); below, at mdpi (48 px): "
               "full colour, themed light, themed dark", font=small, fill=ink, anchor="mm")
        for j, name in enumerate(("ic_launcher.webp", "ic_launcher_round.webp")):
            im = Image.open(os.path.join(ROOT, res, "mipmap-xxxhdpi", name)).convert("RGBA")
            sheet.alpha_composite(im, (490 + j * 215, y0 + 370))
        mono = parse_vector(os.path.join(ROOT, res, "drawable", "new_monochrome.xml"), 192)
        tile = Image.composite(Image.new("RGBA", (192, 192), (30, 30, 40, 255)),
                               Image.new("RGBA", (192, 192), (255, 255, 255, 255)), mono)
        sheet.alpha_composite(tile, (490 + 430, y0 + 370))
        d.text((490 + 310, y0 + 580), "legacy ic_launcher, ic_launcher_round (xxxhdpi); new_monochrome.xml (108 dp)",
               font=small, fill=ink, anchor="mm")
        if module == "app":
            glyph = parse_vector(os.path.join(ROOT, res, "drawable", "pixelplay_base_monochrome.xml"), 140)
            about = Image.new("RGBA", (240, 240), (0, 0, 0, 0))
            ImageDraw.Draw(about).ellipse((0, 0, 239, 239), fill=(229, 222, 255, 255))  # 48 dp circle at 5x
            g = Image.new("RGBA", (140, 140), (71, 63, 119, 255))
            g.putalpha(glyph)  # 28 dp glyph at 5x, 10 dp padding
            about.alpha_composite(g, (50, 50))
            sheet.alpha_composite(about, (490 + 680, y0 + 362))
            d.text((490 + 800, y0 + 618), "About: pixelplay_base_monochrome (5x)", font=small, fill=ink, anchor="mm")
    sheet.convert("RGB").save(path, "PNG", optimize=True)
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--generator", required=True, help="the iOS repo's ci/make-icon.py")
    ap.add_argument("--preview", metavar="OUT.png", help="contact sheet of the written icons")
    ap.add_argument("--preview-only", action="store_true", help="don't write, only render the preview")
    ap.add_argument("--notification-only", action="store_true", help="write only the notification small icon")
    args = ap.parse_args()
    if args.notification_only:
        write_notification_icon(load_generator(args.generator))
    elif not args.preview_only:
        write_all(load_generator(args.generator))
    if args.preview:
        write_preview(args.preview)


if __name__ == "__main__":
    main()
